src/UI/SchoolApp.Web/Controllers/mvc/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SchoolApp.Modul.School.Provider;

namespace SchoolApp.Web.Controllers.mvc
{
    public class MemberController : Controller
    {

        public ISchoolServices _schoolServices;

        public MemberController(ISchoolServices schoolServices)
        {
            _schoolServices = schoolServices;
        }
        public IActionResult Index()
        {
            return View();
        }


        public IActionResult MemberAdd()
        {
            var _parent = _schoolServices.GetParent(HttpContext.Session.GetAuth().Key);
            ViewBag.parent = _parent;
            return View(new MemberViewModel());
        }
        public IActionResult MemberDelete(int id)
        {
            _schoolServices.MemberDelete(id);
            return RedirectToAction("Index");
        }
        public IActionResult MemberDetail(int id)
        {
            var model = _schoolServices.GetMember(HttpContext.Session.GetAuth().Key, id);
            var _parent = _schoolServices.GetParent(HttpContext.Session.GetAuth().Key);
            ViewBag.parent = _parent;
            return View(model);
        }
        [HttpPost]
        public IActionResult MemberUpdate(MemberViewModel model)
        {
            if (model.Id != null && model.Id > 0)
                _schoolServices.MemberUpdate(model);
            else
                _schoolServices.MemberAdd(model);
            return RedirectToAction("Index");
        }


        public IActionResult ParentList()
        {
            var model = _schoolServices.GetParent(HttpContext.Session.GetAuth().Key);
            return View(model);
        }
        [HttpPost]
        public bool ParentAdd(ParentViewModel model)
        {
            return _schoolServices.ParentAdd(model);
        }

        public JsonResult GetMember()
        {
            var model = _schoolServices.GetMember(HttpContext.Session.GetAuth().ActiveSchool);
            return Json(model);
        }
    }
}

src/UI/SchoolApp.Web/Controllers/mvc/NewsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SchoolApp.Modul.Post.Provider;

namespace SchoolApp.Web.Controllers.mvc
{
    public class NewsController : Controller
    {
        ISchoolPostServices _schoolPostServices;

        public NewsController(ISchoolPostServices schoolPostServices)
        {
            _schoolPostServices = schoolPostServices;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AddPost()
        {
            var typeList = _schoolPostServices.GetType();
            ViewBag.type = typeList;
            return View(new SchoolPostViewModel());
        }
        public IActionResult DetailPost(int id)
        {
            var _data = _schoolPostServices.GetSchoolPost(HttpContext.Session.GetAuth().Key, id);
            var typeList = _schoolPostServices.GetType();
            ViewBag.type = typeList;
            return View(_data.Data);
        }
        public IActionResult UpdatePost(SchoolPostViewModel model, IFormFile imgFile)
        {
            model.SchoolId = HttpContext.Session.GetAuth().ActiveSchool;


            if (imgFile != null)
            {
                var filePath = Path.Combine("wwwroot/UploadFile/",
                                   Path.GetRandomFileName()).Replace(".", "") + imgFile.FileName;
                if (System.IO.File.Exists(filePath))
                {
                    System.IO.File.Delete(filePath);
                }
                using (var localFile = System.IO.File.OpenWrite(filePath))
                using (var uploadedFile = imgFile.OpenReadStream())
                {
                    uploadedFile.CopyTo(localFile);
                }

                model.ImgUrl = filePath;
            }

            if (model.Id != null && model.Id > 0)
                _schoolPostServices.Update(model);
            else
                _schoolPostServices.Add(model);
            return RedirectToAction("Index");
        }

        public IActionResult DeletePost(int id)
        {
            _schoolPostServices.Delete(id);
            return RedirectToAction("Index");
        }


        public JsonResult GetNews()
        {
            var _model = _schoolPostServices.GetSchoolPost(HttpContext.Session.GetAuth().ActiveSchool);
            return Json(_model);
        }

    }
}

src/UI/SchoolApp.Web/Views/Member/Add.cshtml
@{
    ViewData["Title"] = "Detail";
}

<h1>Detail</h1>

src/UI/SchoolApp.Web/Views/Member/Index.cshtml
<div class="kt-portlet kt-portlet--mobile">
    <div class="kt-portlet__head kt-portlet__head--lg">
        <div class="kt-portlet__head-label">
            <span class="kt-portlet__head-icon">
                <i class="kt-font-brand flaticon2-line-chart"></i>
            </span>
            <h3 class="kt-portlet__head-title">
             Öğrenci Listesi
            </h3>
        </div>
        <div class="kt-portlet__head-toolbar">
            <div class="kt-portlet__head-wrapper">

                &nbsp;
                <div class="dropdown dropdown-inline">
                    <button type="button" onclick="addFiled()" class="btn btn-brand btn-icon-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="flaticon2-plus"></i> Yeni Ekle
                    </button>     
                    <button type="button" onclick="parentList()" class="btn btn-brand btn-icon-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="flaticon2-plus"></i> Ebeveyn Listesi
                    </button>

                </div>
            </div>
        </div>
    </div>
    <div class="kt-portlet__body">

        <!--begin: Search Form -->
        <div class="kt-form kt-form--label-right kt-margin-t-20 kt-margin-b-10">
            <div class="row align-items-center">
                <div class="col-xl-12 order-2 order-xl-1">
                    <div class="row align-items-center">
                        <div class="col-md-12 kt-margin-b-20-tablet-and-mobile">
                            <div class="kt-input-icon kt-input-icon--left">
                                <input type="text" class="form-control" placeholder="Kayıt Ara ..." id="generalSearch">
                                <span class="kt-input-icon__icon kt-input-icon__icon--left">
                                    <span><i class="la la-search"></i></span>
                                </span>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="col-xl-4 order-1 order-xl-2 kt-align-right">
                    <a href="#" class="btn btn-default kt-hidden">
                        <i class="la la-cart-plus"></i> New Order
                    </a>
                    <div class="kt-separator kt-separator--border-dashed kt-separator--space-lg d-xl-none"></div>
                </div>
            </div>
        </div>

        <!--end: Search Form -->
    </div>
    <div class="kt-portlet__body kt-portlet__body--fit">
        <!--begin: Datatable -->
        <div class="kt-datatable" id="api_events"></div>
        <!--end: Datatable -->
    </div>
    <div class="kt-portlet__body">
        <textarea id="kt_datatable_console" class="form-control kt-margin-t-30" cols="100" rows="10" title="Console" readonly="readonly"></textarea>
        <div class="kt-margin-t-10">
            <button class="btn btn-secondary" type="button" id="kt_datatable_clear">Clear Console</button>
            <button class="btn btn-secondary" type="button" id="kt_datatable_reload">Reload Data</button>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="fieldModal" tabindex="-1" role="dialog" aria-labelledby="fieldModal" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content" id="modalLoadingContent">
           
        </div>
    </div>
</div>





@section Scripts
{
    <script>
        'use strict';
        // Class definition

        var KTDefaultDatatableDemo = function () {
            // Private functions

            // basic demo
            var demo = function () {

                var datatable = $('.kt-datatable').KTDatatable({
                    // datasource definition
                    data: {
                        type: 'remote',
                        source: {
                            read: {
                                url: '/member/getMember',
                            },
                        },
                        pageSize: 5, // display 20 records per page
                        serverPaging: true,
                        serverFiltering: true,
                        serverSorting: true,
                    },

                    // layout definition
                    layout: {
                        scroll: true, // enable/disable datatable scroll both horizontal and vertical when needed.
                        minHeight: null, // datatable's body's fixed height
                        footer: false, // display/hide footer
                    },

                    // column sorting
                    sortable: true,

                    // toolbar
                    toolbar: {
                        // toolbar placement can be at top or bottom or both top and bottom repeated
                        placement: ['bottom'],

                        // toolbar items
                        items: {
                            // pagination
                            pagination: {
                                // page size select
                                pageSizeSelect: [5, 10, 20, 30, 50], // display dropdown to select pagination size. -1 is used for "ALl" option
                            },
                        },
                    },

                    search: {
                        input: $('#generalSearch'),
                    },

                    // columns definition
                    columns: [
                        {
                            field: 'name',
                            title: 'İsim',
                            textAlign: 'center',
                        }, {
                            field: 'surname',
                            title: 'Soyisim',
                            textAlign: 'center',
                        }, {
                            field: 'parentName',
                            title: 'Ebevent',
                            textAlign: 'center',
                        }, {
                            field: 'schoolNo',
                            title: 'Okul No',
                            textAlign: 'center',
                        }, {
                            field: 'Actions',
                            title: 'Actions',
                            sortable: false,
                            width: 110,
                            overflow: 'visible',
                            autoHide: false,
                            template: function (e) {
                                return '\
                                            <a href=" javascript:;" onclick="fieldDetail('+ e.id + ')" class="btn btn-sm btn-clean btn-icon btn-icon-md" title="Edit details">\
                                                <i class="la la-edit"></i>\
                                            </a>\
                                            <a  href="/Member/MemberDelete/'+ e.id + '"  class="btn btn-sm btn-clean btn-icon btn-icon-md" title="Delete">\
                                                <i class="la la-trash"></i>\
                                            </a>\
                                        ';
                            },
                        }],

                });



            };


            return {
                // public functions
                init: function () {
                    demo();
                    eventsCapture();
                },
            };
        }();

        jQuery(document).ready(function () {
            KTDefaultDatatableDemo.init();
        });


        function fieldDetail(id) {
            ajaxModelLoad("/member/MemberDetail/" + id);

        }

        function addFiled() {
            ajaxModelLoad("/member/MemberAdd/");
        }



        function parentList() {
            ajaxModelLoad("/member/ParentList/");

        }

        function ajaxModelLoad(url) {

            $("#fieldModal").modal();
            modalLoading();
            $.ajax({
                url: url,
                type: 'GET',
                success: function (data) {
                    $("#modalLoadingContent").html(data);
                }
            });

        }

        function modalLoading() {
            $("#modalLoadingContent").html("YÜKLENİYOR...");
        }
    </script>

}

src/UI/SchoolApp.Web/Views/Member/MemberAdd.cshtml
@using SchoolApp.Modul.School.Provider
@model MemberViewModel

@{
    Layout = null;
    var parent = (List<ParentViewModel>)ViewBag.parent;
}

<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Yeni Ekle</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<form id="formmember" action="@Url.Action("MemberUpdate", "Member")" method="post">

    <div class="modal-body">

        <div class="kt-portlet__body">
            <div class="kt-section kt-section--first">
                <div class="form-group">
                    <label>İsim:</label>
                    <input type="text" class="form-control" name="Name" value="@Model.Name" required>
                </div>
                <div class="form-group">
                    <label>Soyisim:</label>
                    <input type="text" class="form-control" name="Surname" value="@Model.Surname" required>
                </div>
                <div class="form-group">
                    <label>Okul No:</label>
                    <input type="number" class="form-control" name="SchoolNo" value="@Model.SchoolNo" required>
                </div>
                <div class="form-group">
                    <label>Veli:</label>
                    <select name="ParentId" class="form-control" required>
                        <option value=""></option>
                        @foreach (var pa in parent)
                        {
                            <option value="@pa.Id">@pa.Name @pa.Surname</option>
                        }
                    </select>
                </div>



            </div>
        </div>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">İptal</button>
        <button type="submit" class="btn btn-primary">Kaydet</button>
    </div>
</form>

src/UI/SchoolApp.Web/Views/Member/MemberDetail.cshtml
@using SchoolApp.Modul.School.Provider
@model SchoolApp.Modul.School.Provider.MemberViewModel
@{
    Layout = null;
    var parent = (List<ParentViewModel>)ViewBag.parent;
}

<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Detay</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<form id="formnews" action="@Url.Action("UpdatePost", "News")" method="post">
    <div class="modal-body">
        <input type="hidden" name="Id" value="@Model.Id" />

        <div class="kt-portlet__body">
            <div class="kt-section kt-section--first">
                <div class="form-group">
                    <label>Başlık:</label>
                    <input type="text" class="form-control" name="Name" value="@Model.Name">
                </div>
                <div class="form-group">
                    <label>İçerik:</label>
                    <input type="text" class="form-control" name="Surname" value="@Model.Surname">
                </div>

                <div class="form-group">
                    <label>Veli:</label>
                    <select name="ParentId" class="form-control">
                        @foreach (var pa in parent)
                        {
                          
                        }
                    </select>
                </div>

                @*<div class="form-group">
                    <label>Yayın tarihi:</label>
                    <input type="date" class="form-control" name="SchoolNo" value="@Model.SchoolNo">
                </div>
                <div class="form-group">
                    <label>Bitiş tarihi:</label>
                    <input type="date" class="form-control" name="SchoolNo" value="@Model.SchoolNo">
                </div>*@



            </div>
        </div>



    </div>


    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapat</button>
        <button type="submit" class="btn btn-primary">Kaydet</button>
    </div>

</form>

<script>
    function memberUpdate() {
        var _formSeriliaz = $("#formmember").serialize();
        $.ajax({
            url: "/member/update",
            type: 'POST',
            data: _formSeriliaz,
            success: function (data) {
                alert(data);
            }
        });
    }
</script>

src/UI/SchoolApp.Web/Views/Member/ParentList.cshtml
@using SchoolApp.Modul.School.Provider
@model List<ParentViewModel>
@{
    Layout = null;
}

<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Ebeveyn Listesi</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    @*<input type="hidden" name="Id" value="@Model.Id" />*@

    <div class="kt-portlet__body">
        <div class="kt-section kt-section--first">
            @*<div class="form-group">
                    <label>İsim:</label>
                    <input type="text" class="form-control" name="Name" value="@Model.Name">
                </div>
                <div class="form-group">
                    <label>Soyisim:</label>
                    <input type="text" class="form-control" name="Surname" value="@Model.Surname">
                </div>
                <div class="form-group">
                    <label>Okul No:</label>
                    <input type="number" class="form-control" name="SchoolNo" value="@Model.SchoolNo">
                </div>*@



        </div>

        <table class="table">
            <thead>
                <tr>
                    <th scope="col">İsim</th>
                    <th scope="col">Soyisim</th>
                    <th scope="col">App Şiffre</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var p in Model)
                {
                    <tr>
                        <td> @p.Name </td>
                        <td>@p.Surname</td>
                        <td>--</td>
                    </tr>
                }

            </tbody>
        </table>




    </div>



</div>


<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapat</button>
</div>


<script>
    function memberUpdate() {
        var _formSeriliaz = $("#formmember").serialize();
        $.ajax({
            url: "/member/update",
            type: 'POST',
            data: _formSeriliaz,
            success: function (data) {
                alert(data);
            }
        });
    }
</script>